service: lms-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  stage: prod
  environment:
    CLERK_SECRET_KEY: ${env:CLERK_SECRET_KEY}
    CLERK_PUBLISHABLE_KEY: ${env:CLERK_PUBLISHABLE_KEY}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    CLOUDFRONT_DOMAIN: ${env:CLOUDFRONT_DOMAIN}
    NODE_ENV: production

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedMethods:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/*

package:
  include:
    - src/seed/data/**


functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any
  # Seeding function to populate the database
  seed:
    handler: src/seed.handler

plugins:
  - serverless-offline
