name: Build Frontend and Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-client:
    name: Build Client (Next.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build client with Clerk Key
        working-directory: ./client
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
        run: npm run build

  build-server:
    name: Build Server (TypeScript Express)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./server
        run: npm install

      - name: Build server
        working-directory: ./server
        run: npm run build
